<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Api Documentation</title>
    <link rel="stylesheet" href="<?= $_ENV["APIDOC_PATH"] ?>/assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="<?= $_ENV["APIDOC_PATH"] ?>/assets/js/app.js"></script>
</head>
<body>
    <div class="doc-head">
        <h1>Documentation</h1>
        <p>This documentation is auto-generated by MicroFramework</p>
    </div>
    <div class="doc-content">
        <div class="endpoints">
            <div class="endpoint">
                <div class="endpoint-header first-endpoint">
                    <h3 class="method blue">Get</h3>
                    <h3>/endpoint/{id:integer} </h3>
                    <p>A little description (Optionnal)</p>
                    <div class="right">
                        <button class="btn outline-blue"><i class="fa-solid fa-clipboard"></i> Copy The Path !</button>
                    </div>
                </div>

                <div class="endpoint-body">
                    <div class="parameters">
                        <h4 class="p-title">Parameters</h4>
                        <div class="p-body">
                            <form class="f-params">
                                <div class="p-section">
                                    <h5 class="param-name">id</h5>
                                    <input type="text" class="p-input" placeholder="id">
                                </div>
                                <button class="btn btn-try outline-blue">Launch Test</button>
                            </form>
                        </div>
                    </div>
                    <div class="result">
                        <h4 class="r-title">Result</h4>

                    </div>
                </div>
            </div>
            <div class="endpoint">
                <div class="endpoint-header">
                    <h3 class="method green">POST</h3>
                    <h3>/endpoint/{id} </h3>
                    <p>A little description (Optionnal)</p>
                    <div class="right">
                        <button class="btn outline-green"><i class="fa-solid fa-clipboard"></i> Copy The Path !</button>
                    </div>
                </div>

                <!--<div class="endpoint-body">
                    <div class="parameters">
                        <h4 class="p-title">Query Parameters</h4>
                        <div class="p-body">

                        </div>
                    </div>
                </div>-->
            </div>
            <div class="endpoint">
                <div class="endpoint-header">
                    <h3 class="method red">DELETE</h3>
                    <h3>/endpoint/{id} </h3>
                    <p>A little description (Optionnal)</p>
                    <div class="right">
                        <button class="btn outline-red"><i class="fa-solid fa-clipboard"></i> Copy The Path !</button>
                    </div>
                </div>

                <!--<div class="endpoint-body">
                    <div class="parameters">
                        <h4 class="p-title">Query Parameters</h4>
                        <div class="p-body">

                        </div>
                    </div>
                </div>-->
            </div>
            <div class="endpoint">
                <div class="endpoint-header last-endpoint">
                    <h3 class="method light-blue">PUT</h3>
                    <h3>/endpoint/{id} </h3>
                    <p>A little description (Optionnal)</p>
                    <div class="right">
                        <button class="btn outline-light-blue"><i class="fa-solid fa-clipboard"></i> Copy The Path !</button>
                    </div>
                </div>

                <!--<div class="endpoint-body">
                    <div class="parameters">
                        <h4 class="p-title">Query Parameters</h4>
                        <div class="p-body">

                        </div>
                    </div>
                </div>-->
            </div>
            <?php
            /*if (isset($args["GET"]))
            {
                ?>
                <div class="endpoint">
                    <h1 class='method'>Get Method</h1>
                <?php
                foreach ($args["GET"] as $get)
                {
                    if ($get["endpoint"]->getName() != "api-documentation")
                    {
                        ?>

                        <div class="endpoint-header">
                            <h3>/<?= $get["endpoint"]->getPath() ?></h3>
                            <?php if ($get["endpoint"]->getDescription()) { ?>  <p><?= $get["endpoint"]->getDescription() ?></p> <?php } ?>
                        </div>
                        <?php
                    }
                }
                ?>
                </div>
                <?php
            }
            ?>
            <?php
            if (isset($args["GET"]))
            {
                ?>
                <div class="endpoint">
                <h1 class='method'>Get Method:</h1>
                <?php
                foreach ($args["GET"] as $get)
                {
                    if ($get["endpoint"]->getName() != "api-documentation")
                    {
                        ?>

                        <div class="endpoint-header">
                            <h3>/<?= $get["endpoint"]->getPath() ?></h3>
                            <?php if ($get["endpoint"]->getDescription()) { ?>  <p><?= $get["endpoint"]->getDescription() ?></p> <?php } ?>
                        </div>
                        </div>
                        <?php
                    }
                }
            }
            */?>
        </div>
    </div>
</body>
</html>